package mall.entity.mall;

import java.io.Serializable;
import java.util.Date;

public class MallUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.gender
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.last_login_ip
     *
     * @mbggenerated
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.user_level
     *
     * @mbggenerated
     */
    private Byte userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.wx_openid
     *
     * @mbggenerated
     */
    private String wxOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.share_user_id
     *
     * @mbggenerated
     */
    private Integer shareUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.viplevel
     *
     * @mbggenerated
     */
    private Byte viplevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mall_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.id
     *
     * @return the value of mall_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.id
     *
     * @param id the value for mall_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.username
     *
     * @return the value of mall_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.username
     *
     * @param username the value for mall_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.password
     *
     * @return the value of mall_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.password
     *
     * @param password the value for mall_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.gender
     *
     * @return the value of mall_user.gender
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.gender
     *
     * @param gender the value for mall_user.gender
     *
     * @mbggenerated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.birthday
     *
     * @return the value of mall_user.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.birthday
     *
     * @param birthday the value for mall_user.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.last_login_time
     *
     * @return the value of mall_user.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.last_login_time
     *
     * @param lastLoginTime the value for mall_user.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.last_login_ip
     *
     * @return the value of mall_user.last_login_ip
     *
     * @mbggenerated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.last_login_ip
     *
     * @param lastLoginIp the value for mall_user.last_login_ip
     *
     * @mbggenerated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.user_level
     *
     * @return the value of mall_user.user_level
     *
     * @mbggenerated
     */
    public Byte getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.user_level
     *
     * @param userLevel the value for mall_user.user_level
     *
     * @mbggenerated
     */
    public void setUserLevel(Byte userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.nickname
     *
     * @return the value of mall_user.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.nickname
     *
     * @param nickname the value for mall_user.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.mobile
     *
     * @return the value of mall_user.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.mobile
     *
     * @param mobile the value for mall_user.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.avatar
     *
     * @return the value of mall_user.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.avatar
     *
     * @param avatar the value for mall_user.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.wx_openid
     *
     * @return the value of mall_user.wx_openid
     *
     * @mbggenerated
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.wx_openid
     *
     * @param wxOpenid the value for mall_user.wx_openid
     *
     * @mbggenerated
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.status
     *
     * @return the value of mall_user.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.status
     *
     * @param status the value for mall_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.add_time
     *
     * @return the value of mall_user.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.add_time
     *
     * @param addTime the value for mall_user.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.update_time
     *
     * @return the value of mall_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.update_time
     *
     * @param updateTime the value for mall_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.deleted
     *
     * @return the value of mall_user.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.deleted
     *
     * @param deleted the value for mall_user.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.share_user_id
     *
     * @return the value of mall_user.share_user_id
     *
     * @mbggenerated
     */
    public Integer getShareUserId() {
        return shareUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.share_user_id
     *
     * @param shareUserId the value for mall_user.share_user_id
     *
     * @mbggenerated
     */
    public void setShareUserId(Integer shareUserId) {
        this.shareUserId = shareUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.viplevel
     *
     * @return the value of mall_user.viplevel
     *
     * @mbggenerated
     */
    public Byte getViplevel() {
        return viplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.viplevel
     *
     * @param viplevel the value for mall_user.viplevel
     *
     * @mbggenerated
     */
    public void setViplevel(Byte viplevel) {
        this.viplevel = viplevel;
    }
}