package mall.entity.mall;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MallUserAccount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user_account.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user_account.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user_account.remain_amount
     *
     * @mbggenerated
     */
    private BigDecimal remainAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user_account.total_amount
     *
     * @mbggenerated
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user_account.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user_account.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user_account.settlement_rate
     *
     * @mbggenerated
     */
    private Integer settlementRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user_account.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user_account.share_url
     *
     * @mbggenerated
     */
    private String shareUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user_account.id
     *
     * @return the value of mall_user_account.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user_account.id
     *
     * @param id the value for mall_user_account.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user_account.user_id
     *
     * @return the value of mall_user_account.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user_account.user_id
     *
     * @param userId the value for mall_user_account.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user_account.remain_amount
     *
     * @return the value of mall_user_account.remain_amount
     *
     * @mbggenerated
     */
    public BigDecimal getRemainAmount() {
        return remainAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user_account.remain_amount
     *
     * @param remainAmount the value for mall_user_account.remain_amount
     *
     * @mbggenerated
     */
    public void setRemainAmount(BigDecimal remainAmount) {
        this.remainAmount = remainAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user_account.total_amount
     *
     * @return the value of mall_user_account.total_amount
     *
     * @mbggenerated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user_account.total_amount
     *
     * @param totalAmount the value for mall_user_account.total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user_account.create_time
     *
     * @return the value of mall_user_account.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user_account.create_time
     *
     * @param createTime the value for mall_user_account.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user_account.modify_time
     *
     * @return the value of mall_user_account.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user_account.modify_time
     *
     * @param modifyTime the value for mall_user_account.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user_account.settlement_rate
     *
     * @return the value of mall_user_account.settlement_rate
     *
     * @mbggenerated
     */
    public Integer getSettlementRate() {
        return settlementRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user_account.settlement_rate
     *
     * @param settlementRate the value for mall_user_account.settlement_rate
     *
     * @mbggenerated
     */
    public void setSettlementRate(Integer settlementRate) {
        this.settlementRate = settlementRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user_account.status
     *
     * @return the value of mall_user_account.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user_account.status
     *
     * @param status the value for mall_user_account.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user_account.share_url
     *
     * @return the value of mall_user_account.share_url
     *
     * @mbggenerated
     */
    public String getShareUrl() {
        return shareUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user_account.share_url
     *
     * @param shareUrl the value for mall_user_account.share_url
     *
     * @mbggenerated
     */
    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl;
    }
}