package mall.mapper.mall;

import java.util.List;
import mall.entity.mall.MallAddress;
import mall.entity.mall.MallAddressExample;
import org.apache.ibatis.annotations.Param;

public interface MallAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbggenerated
     */
    int countByExample(MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbggenerated
     */
    int deleteByExample(MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbggenerated
     */
    int insert(MallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbggenerated
     */
    int insertSelective(MallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbggenerated
     */
    List<MallAddress> selectByExample(MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbggenerated
     */
    MallAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MallAddress record, @Param("example") MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MallAddress record, @Param("example") MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MallAddress record);

    MallAddress selectOneByExample(MallAddressExample example);

}