package mall.mapper.mall;

import java.util.List;
import mall.entity.mall.MallOrder;
import mall.entity.mall.MallOrderExample;
import org.apache.ibatis.annotations.Param;

public interface MallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int countByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int deleteByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int insert(MallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int insertSelective(MallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    List<MallOrder> selectByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    MallOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MallOrder record, @Param("example") MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MallOrder record, @Param("example") MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MallOrder record);
}