package mall.mapper.mall;

import java.util.List;
import mall.entity.mall.MallGoodsAttribute;
import mall.entity.mall.MallGoodsAttributeExample;
import org.apache.ibatis.annotations.Param;

public interface MallGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbggenerated
     */
    int countByExample(MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbggenerated
     */
    int deleteByExample(MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbggenerated
     */
    int insert(MallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbggenerated
     */
    int insertSelective(MallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbggenerated
     */
    List<MallGoodsAttribute> selectByExample(MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbggenerated
     */
    MallGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MallGoodsAttribute record, @Param("example") MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MallGoodsAttribute record, @Param("example") MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MallGoodsAttribute record);
}