package mall.mapper.mall;

import java.util.List;
import mall.entity.mall.MallUserAccount;
import mall.entity.mall.MallUserAccountExample;
import org.apache.ibatis.annotations.Param;

public interface MallUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    int countByExample(MallUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    int deleteByExample(MallUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    int insert(MallUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    int insertSelective(MallUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    List<MallUserAccount> selectByExample(MallUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    MallUserAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MallUserAccount record, @Param("example") MallUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MallUserAccount record, @Param("example") MallUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MallUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_user_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MallUserAccount record);
}