package mall.mapper.mall;

import java.util.List;
import mall.entity.mall.MallGoodsSpecification;
import mall.entity.mall.MallGoodsSpecificationExample;
import org.apache.ibatis.annotations.Param;

public interface MallGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbggenerated
     */
    int countByExample(MallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbggenerated
     */
    int deleteByExample(MallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbggenerated
     */
    int insert(MallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbggenerated
     */
    int insertSelective(MallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbggenerated
     */
    List<MallGoodsSpecification> selectByExample(MallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbggenerated
     */
    MallGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MallGoodsSpecification record, @Param("example") MallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MallGoodsSpecification record, @Param("example") MallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MallGoodsSpecification record);
}